### ISSUE TITLE
Make the site work with the latest version of Laravel Framework

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-sample-app-php#8] opened 2019-04-09 07:33 UTC
### Motivation

Make sure the site is up to date with the latest standards.

### Proposed solution

Update Laravel to v5.7.x.

### Acceptance criteria
- [ ] tests are passing
- [ ] the site builds
- [ ] no runtime errors when browsing the application as described here: https://github.com/Kentico/kentico-cloud-sample-app-php/#application-setup

**Comment by petrsvihlik** [comment] 2019-04-09 07:35
would you like to pick it up @shennawy?

**Comment by nikspyratos** [comment] 2019-10-07 15:04
Is this still up for grabs? I'll take it if so. Should be able to get it to 6.x now.

**Comment by Simply007** [comment] 2019-10-08 08:38
Hello @nikolaos-spyratos. 
I've just sent you an invitation to the Kentico GitHub organization. If you accept it, you'll be able to interact with other Kentico GitHub community members in out [Global collaborators dicsussions](https://github.com/orgs/Kentico/teams/global-collaborators) as well as getting the fresh info about Kentico Github activity.

**The issue is yours!**

Note:
I have just found a fix of an infinite loop of destructing calls (https://sourceforge.net/p/simplehtmldom/support-requests/49/).
As a part of that, I have also merged the pull request #10  with @dusekdan so that the app is ready for the Laravel update!

**Closed as completed** 2020-04-07 10:41 UTC
Labels: help wanted, good first issue, groomed, up-for-grabs, hacktoberfest
